link:	utils.o main.o vettore.o 
	gcc utils.o main.o vettore.o -o array.exe
	
utils.o:
	gcc -c utils.c
	
main.o:
	gcc -c main.c
	
vettore.o:
	gcc -c vettore.c
	
clean:
	rm -f utils.o main.o vettore.o array.exe
	