link : main.o stack.o item.o list.o
	gcc main.o stack.o item.o list.o -o parentesi.exe
	
main.o :
	gcc -c main.c
	
stack.o :
	gcc -c stack.c
	
item.o :
	gcc -c item.c
	
list.o :
	gcc -c list.c
	
clean :
	rm -f main.o stack.o item.o list.o parentesi.exe
	