void input_array(int *a, int n);
void output_array(int *a, int n);
int min( int *a, int n);
void selection_sort(int *a, int n);
void insertSortedArray(int *array, int *size, int element);
void insertion_sort(int *array, int size);
void bubbleSort(int *arr, int n);
int adaptiveBubbleSort(int *array, int n);
int ricercaBin(int *arr, int n,int element);
int ricercaLineare(int *arr, int n, int el);