link: playlist.o song.o list.o utils.o item.o main.o 
	gcc playlist.o song.o list.o utils.o item.o main.o -o adtPlaylist.exe
	
playlist.o:
	gcc -c playlist.c
	
song.o:
	gcc -c song.c
	
list.o:
	gcc -c list.c
	
utils.o:
	gcc -c utils.c
	
item.o:
	gcc -c item.c
	
main.o:
	gcc -c main.c
	
clean:
	rm -f playlist.o song.o list.o utils.o item.o main.o adtPlaylist.exe
	