link :	utils.o vettore.o alloc.o
	gcc utils.o vettore.o alloc.o -o vettore.exe
	
utils.o :
	gcc -c utils.c
	
vettore.o :
	gcc -c vettore.c
	
alloc.o :
	gcc -c alloc.c
	
clean: 
	rm -f utils.o vettore.o alloc.o vettore.exe