link: playlist.o songs.o list.o utils.o item.o main.o 
	gcc playlist.o songs.o list.o utils.o item.o main.o -o adtMusica.exe
	
playlist.o:
	gcc -c playlist.c
	
songs.o:
	gcc -c songs.c
	
list.o:
	gcc -c list.c
	
utils.o:
	gcc -c utils.c
	
item.o:
	gcc -c item.c
	
main.o:
	gcc -c main.c
	
clean:
	rm -f playlist.o songs.o list.o utils.o item.o main.o adtMusica.exe
	