link:	esame.o item.o libretto.o list.o main.o utils.o 
	gcc esame.o item.o libretto.o list.o main.o utils.o -o adtScuola.exe
	
esame.o:
	gcc -c esame.c
	
item.o:
	gcc -c item.c
	
libretto.o:
	gcc -c libretto.c

list.o:
	gcc -c list.c
	
main.o:
	gcc -c main.c
	
utils.o:
	gcc -c utils.c
	
clean:
	rm -f esame.o item.o libretto.o list.o main.o utils.o adtScuola.exe